// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        (unknown)
// source: replicationMessage.proto

package proto_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// https://developers.google.com/protocol-buffers/docs/proto?csw=1#scalar
type ReplicationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CUuids  []uint64          `protobuf:"varint,1,rep,packed,name=c_uuids,json=cUuids,proto3" json:"c_uuids,omitempty"`
	MsgMime map[string]string `protobuf:"bytes,2,rep,name=msg_mime,json=msgMime,proto3" json:"msg_mime,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Msg     []byte            `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ReplicationMessage) Reset() {
	*x = ReplicationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationMessage) ProtoMessage() {}

func (x *ReplicationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_replicationMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationMessage.ProtoReflect.Descriptor instead.
func (*ReplicationMessage) Descriptor() ([]byte, []int) {
	return file_replicationMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicationMessage) GetCUuids() []uint64 {
	if x != nil {
		return x.CUuids
	}
	return nil
}

func (x *ReplicationMessage) GetMsgMime() map[string]string {
	if x != nil {
		return x.MsgMime
	}
	return nil
}

func (x *ReplicationMessage) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_replicationMessage_proto protoreflect.FileDescriptor

var file_replicationMessage_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x77, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x22, 0xc1, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x63, 0x55,
	0x75, 0x69, 0x64, 0x73, 0x12, 0x44, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x6d, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x77, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x4d, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x3a, 0x0a, 0x0c,
	0x4d, 0x73, 0x67, 0x4d, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_replicationMessage_proto_rawDescOnce sync.Once
	file_replicationMessage_proto_rawDescData = file_replicationMessage_proto_rawDesc
)

func file_replicationMessage_proto_rawDescGZIP() []byte {
	file_replicationMessage_proto_rawDescOnce.Do(func() {
		file_replicationMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_replicationMessage_proto_rawDescData)
	})
	return file_replicationMessage_proto_rawDescData
}

var file_replicationMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_replicationMessage_proto_goTypes = []interface{}{
	(*ReplicationMessage)(nil), // 0: wsholder.ReplicationMessage
	nil,                        // 1: wsholder.ReplicationMessage.MsgMimeEntry
}
var file_replicationMessage_proto_depIdxs = []int32{
	1, // 0: wsholder.ReplicationMessage.msg_mime:type_name -> wsholder.ReplicationMessage.MsgMimeEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_replicationMessage_proto_init() }
func file_replicationMessage_proto_init() {
	if File_replicationMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_replicationMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_replicationMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_replicationMessage_proto_goTypes,
		DependencyIndexes: file_replicationMessage_proto_depIdxs,
		MessageInfos:      file_replicationMessage_proto_msgTypes,
	}.Build()
	File_replicationMessage_proto = out.File
	file_replicationMessage_proto_rawDesc = nil
	file_replicationMessage_proto_goTypes = nil
	file_replicationMessage_proto_depIdxs = nil
}
