// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        (unknown)
// source: ReplicationMsg.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ReplicationMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ReplicationMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ReplicationMsg_proto_rawDescGZIP(), []int{0}
}

type ReplicationMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CUuids  []uint64          `protobuf:"varint,1,rep,packed,name=c_uuids,json=cUuids,proto3" json:"c_uuids,omitempty"`
	MsgMime map[string]string `protobuf:"bytes,2,rep,name=msg_mime,json=msgMime,proto3" json:"msg_mime,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Msg     []byte            `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ReplicationMsg) Reset() {
	*x = ReplicationMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ReplicationMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationMsg) ProtoMessage() {}

func (x *ReplicationMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ReplicationMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationMsg.ProtoReflect.Descriptor instead.
func (*ReplicationMsg) Descriptor() ([]byte, []int) {
	return file_ReplicationMsg_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicationMsg) GetCUuids() []uint64 {
	if x != nil {
		return x.CUuids
	}
	return nil
}

func (x *ReplicationMsg) GetMsgMime() map[string]string {
	if x != nil {
		return x.MsgMime
	}
	return nil
}

func (x *ReplicationMsg) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_ReplicationMsg_proto protoreflect.FileDescriptor

var file_ReplicationMsg_proto_rawDesc = []byte{
	0x0a, 0x14, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0xb3, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x63, 0x55, 0x75, 0x69, 0x64, 0x73, 0x12,
	0x3a, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x6d, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x4d, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x3a, 0x0a,
	0x0c, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x3b, 0x0a, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x0d, 0x4c, 0x6f, 0x74, 0x73, 0x4f, 0x66, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x65, 0x73, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x73, 0x67, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ReplicationMsg_proto_rawDescOnce sync.Once
	file_ReplicationMsg_proto_rawDescData = file_ReplicationMsg_proto_rawDesc
)

func file_ReplicationMsg_proto_rawDescGZIP() []byte {
	file_ReplicationMsg_proto_rawDescOnce.Do(func() {
		file_ReplicationMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_ReplicationMsg_proto_rawDescData)
	})
	return file_ReplicationMsg_proto_rawDescData
}

var file_ReplicationMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ReplicationMsg_proto_goTypes = []interface{}{
	(*Empty)(nil),          // 0: pb.Empty
	(*ReplicationMsg)(nil), // 1: pb.ReplicationMsg
	nil,                    // 2: pb.ReplicationMsg.MsgMimeEntry
}
var file_ReplicationMsg_proto_depIdxs = []int32{
	2, // 0: pb.ReplicationMsg.msg_mime:type_name -> pb.ReplicationMsg.MsgMimeEntry
	0, // 1: pb.Service.LotsOfReplies:input_type -> pb.Empty
	1, // 2: pb.Service.LotsOfReplies:output_type -> pb.ReplicationMsg
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ReplicationMsg_proto_init() }
func file_ReplicationMsg_proto_init() {
	if File_ReplicationMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ReplicationMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ReplicationMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicationMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ReplicationMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ReplicationMsg_proto_goTypes,
		DependencyIndexes: file_ReplicationMsg_proto_depIdxs,
		MessageInfos:      file_ReplicationMsg_proto_msgTypes,
	}.Build()
	File_ReplicationMsg_proto = out.File
	file_ReplicationMsg_proto_rawDesc = nil
	file_ReplicationMsg_proto_goTypes = nil
	file_ReplicationMsg_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	LotsOfReplies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Service_LotsOfRepliesClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) LotsOfReplies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Service_LotsOfRepliesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[0], "/pb.Service/LotsOfReplies", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceLotsOfRepliesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_LotsOfRepliesClient interface {
	Recv() (*ReplicationMsg, error)
	grpc.ClientStream
}

type serviceLotsOfRepliesClient struct {
	grpc.ClientStream
}

func (x *serviceLotsOfRepliesClient) Recv() (*ReplicationMsg, error) {
	m := new(ReplicationMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	LotsOfReplies(*Empty, Service_LotsOfRepliesServer) error
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) LotsOfReplies(*Empty, Service_LotsOfRepliesServer) error {
	return status.Errorf(codes.Unimplemented, "method LotsOfReplies not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_LotsOfReplies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).LotsOfReplies(m, &serviceLotsOfRepliesServer{stream})
}

type Service_LotsOfRepliesServer interface {
	Send(*ReplicationMsg) error
	grpc.ServerStream
}

type serviceLotsOfRepliesServer struct {
	grpc.ServerStream
}

func (x *serviceLotsOfRepliesServer) Send(m *ReplicationMsg) error {
	return x.ServerStream.SendMsg(m)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LotsOfReplies",
			Handler:       _Service_LotsOfReplies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ReplicationMsg.proto",
}
