// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.12.0
// source: RepMsg.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RepMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_RepMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_RepMsg_proto_rawDescGZIP(), []int{0}
}

// TODO Maybe add (resource string) to indicate http resource?
// Can be done with msg_mime['Resource'] to overcome issue
// TODO add meta information to indicate:
//      + message for all.
//      + message for all with given prefix
type ReplicationMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CUuids []uint64  `protobuf:"varint,1,rep,packed,name=c_uuids,json=cUuids,proto3" json:"c_uuids,omitempty"`
	Msg    []byte    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Meta   *Metadata `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *ReplicationMsg) Reset() {
	*x = ReplicationMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RepMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationMsg) ProtoMessage() {}

func (x *ReplicationMsg) ProtoReflect() protoreflect.Message {
	mi := &file_RepMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationMsg.ProtoReflect.Descriptor instead.
func (*ReplicationMsg) Descriptor() ([]byte, []int) {
	return file_RepMsg_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicationMsg) GetCUuids() []uint64 {
	if x != nil {
		return x.CUuids
	}
	return nil
}

func (x *ReplicationMsg) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ReplicationMsg) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UniMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  []byte    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Meta *Metadata `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *UniMsg) Reset() {
	*x = UniMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RepMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniMsg) ProtoMessage() {}

func (x *UniMsg) ProtoReflect() protoreflect.Message {
	mi := &file_RepMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniMsg.ProtoReflect.Descriptor instead.
func (*UniMsg) Descriptor() ([]byte, []int) {
	return file_RepMsg_proto_rawDescGZIP(), []int{2}
}

func (x *UniMsg) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *UniMsg) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource         string               `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"` // The resource contains the parent-id and child-id
	Poster           string               `protobuf:"bytes,2,opt,name=poster,proto3" json:"poster,omitempty"`     // Id of the user that posted this issue
	Arrived          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=arrived,proto3" json:"arrived,omitempty"`
	OriginalLocation string               `protobuf:"bytes,4,opt,name=originalLocation,proto3" json:"originalLocation,omitempty"` // Could use custom bits
	MsgMime          map[string]string    `protobuf:"bytes,5,rep,name=msg_mime,json=msgMime,proto3" json:"msg_mime,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Other            map[string]string    `protobuf:"bytes,6,rep,name=other,proto3" json:"other,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RepMsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_RepMsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_RepMsg_proto_rawDescGZIP(), []int{3}
}

func (x *Metadata) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Metadata) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *Metadata) GetArrived() *timestamp.Timestamp {
	if x != nil {
		return x.Arrived
	}
	return nil
}

func (x *Metadata) GetOriginalLocation() string {
	if x != nil {
		return x.OriginalLocation
	}
	return ""
}

func (x *Metadata) GetMsgMime() map[string]string {
	if x != nil {
		return x.MsgMime
	}
	return nil
}

func (x *Metadata) GetOther() map[string]string {
	if x != nil {
		return x.Other
	}
	return nil
}

var File_RepMsg_proto protoreflect.FileDescriptor

var file_RepMsg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x52, 0x65, 0x70, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x5d, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x63, 0x55, 0x75, 0x69, 0x64, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x20, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x22, 0x3c, 0x0a, 0x06, 0x55, 0x6e, 0x69, 0x4d, 0x73, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x20, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65,
	0x74, 0x61, 0x22, 0xfb, 0x02, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x6d, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x4d, 0x69, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x1a, 0x3a, 0x0a, 0x0c, 0x4d, 0x73,
	0x67, 0x4d, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x38, 0x0a, 0x0a, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x32, 0x36, 0x0a, 0x06, 0x77, 0x73, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x2c, 0x0a, 0x09, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x1a, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x32, 0x33, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0d, 0x4c, 0x6f, 0x74, 0x73, 0x4f, 0x66, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x65, 0x73, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x6e, 0x69, 0x4d, 0x73, 0x67, 0x30, 0x01, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RepMsg_proto_rawDescOnce sync.Once
	file_RepMsg_proto_rawDescData = file_RepMsg_proto_rawDesc
)

func file_RepMsg_proto_rawDescGZIP() []byte {
	file_RepMsg_proto_rawDescOnce.Do(func() {
		file_RepMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_RepMsg_proto_rawDescData)
	})
	return file_RepMsg_proto_rawDescData
}

var file_RepMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_RepMsg_proto_goTypes = []interface{}{
	(*Empty)(nil),               // 0: pb.Empty
	(*ReplicationMsg)(nil),      // 1: pb.ReplicationMsg
	(*UniMsg)(nil),              // 2: pb.UniMsg
	(*Metadata)(nil),            // 3: pb.Metadata
	nil,                         // 4: pb.Metadata.MsgMimeEntry
	nil,                         // 5: pb.Metadata.OtherEntry
	(*timestamp.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_RepMsg_proto_depIdxs = []int32{
	3, // 0: pb.ReplicationMsg.meta:type_name -> pb.Metadata
	3, // 1: pb.UniMsg.meta:type_name -> pb.Metadata
	6, // 2: pb.Metadata.arrived:type_name -> google.protobuf.Timestamp
	4, // 3: pb.Metadata.msg_mime:type_name -> pb.Metadata.MsgMimeEntry
	5, // 4: pb.Metadata.other:type_name -> pb.Metadata.OtherEntry
	1, // 5: pb.wsBack.Replicate:input_type -> pb.ReplicationMsg
	0, // 6: pb.Service.LotsOfReplies:input_type -> pb.Empty
	0, // 7: pb.wsBack.Replicate:output_type -> pb.Empty
	2, // 8: pb.Service.LotsOfReplies:output_type -> pb.UniMsg
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_RepMsg_proto_init() }
func file_RepMsg_proto_init() {
	if File_RepMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RepMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RepMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicationMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RepMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RepMsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RepMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_RepMsg_proto_goTypes,
		DependencyIndexes: file_RepMsg_proto_depIdxs,
		MessageInfos:      file_RepMsg_proto_msgTypes,
	}.Build()
	File_RepMsg_proto = out.File
	file_RepMsg_proto_rawDesc = nil
	file_RepMsg_proto_goTypes = nil
	file_RepMsg_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WsBackClient is the client API for WsBack service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WsBackClient interface {
	Replicate(ctx context.Context, opts ...grpc.CallOption) (WsBack_ReplicateClient, error)
}

type wsBackClient struct {
	cc grpc.ClientConnInterface
}

func NewWsBackClient(cc grpc.ClientConnInterface) WsBackClient {
	return &wsBackClient{cc}
}

func (c *wsBackClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (WsBack_ReplicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WsBack_serviceDesc.Streams[0], "/pb.wsBack/Replicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &wsBackReplicateClient{stream}
	return x, nil
}

type WsBack_ReplicateClient interface {
	Send(*ReplicationMsg) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type wsBackReplicateClient struct {
	grpc.ClientStream
}

func (x *wsBackReplicateClient) Send(m *ReplicationMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *wsBackReplicateClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WsBackServer is the server API for WsBack service.
type WsBackServer interface {
	Replicate(WsBack_ReplicateServer) error
}

// UnimplementedWsBackServer can be embedded to have forward compatible implementations.
type UnimplementedWsBackServer struct {
}

func (*UnimplementedWsBackServer) Replicate(WsBack_ReplicateServer) error {
	return status.Errorf(codes.Unimplemented, "method Replicate not implemented")
}

func RegisterWsBackServer(s *grpc.Server, srv WsBackServer) {
	s.RegisterService(&_WsBack_serviceDesc, srv)
}

func _WsBack_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WsBackServer).Replicate(&wsBackReplicateServer{stream})
}

type WsBack_ReplicateServer interface {
	SendAndClose(*Empty) error
	Recv() (*ReplicationMsg, error)
	grpc.ServerStream
}

type wsBackReplicateServer struct {
	grpc.ServerStream
}

func (x *wsBackReplicateServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *wsBackReplicateServer) Recv() (*ReplicationMsg, error) {
	m := new(ReplicationMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _WsBack_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.wsBack",
	HandlerType: (*WsBackServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Replicate",
			Handler:       _WsBack_Replicate_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "RepMsg.proto",
}

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	LotsOfReplies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Service_LotsOfRepliesClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) LotsOfReplies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Service_LotsOfRepliesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[0], "/pb.Service/LotsOfReplies", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceLotsOfRepliesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_LotsOfRepliesClient interface {
	Recv() (*UniMsg, error)
	grpc.ClientStream
}

type serviceLotsOfRepliesClient struct {
	grpc.ClientStream
}

func (x *serviceLotsOfRepliesClient) Recv() (*UniMsg, error) {
	m := new(UniMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	LotsOfReplies(*Empty, Service_LotsOfRepliesServer) error
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) LotsOfReplies(*Empty, Service_LotsOfRepliesServer) error {
	return status.Errorf(codes.Unimplemented, "method LotsOfReplies not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_LotsOfReplies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).LotsOfReplies(m, &serviceLotsOfRepliesServer{stream})
}

type Service_LotsOfRepliesServer interface {
	Send(*UniMsg) error
	grpc.ServerStream
}

type serviceLotsOfRepliesServer struct {
	grpc.ServerStream
}

func (x *serviceLotsOfRepliesServer) Send(m *UniMsg) error {
	return x.ServerStream.SendMsg(m)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LotsOfReplies",
			Handler:       _Service_LotsOfReplies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "RepMsg.proto",
}
